name: Manual Trigger Workflow

on:
  workflow_dispatch:

jobs:
 build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: setup Docker
      uses: docker-practice/actions-setup-docker@master
      timeout-minutes: 12
    - run: |
        docker --version
    - name: image
      run: |
        docker pull nginx
    - name: docker image
      run: |
        docker images 
    - name: tag image
      run: |
        docker tag nginx adrehmanasghar/test1:2 
    - name: login
      run: |
        docker login -u adrehmanasghar -p dckr_pat_YlPDdKJCtY8ZnBzNXDoW26N8dZ4
    # Add your build steps here
    - name: Build application
      run: |
        # Your build commands here
        echo "Building application..."
 push: 
    name: Push
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: setup Docker
      uses: docker-practice/actions-setup-docker@master
      timeout-minutes: 12
    - run: |
        docker --version
    # Add your build steps here
    - name: Build application
      run: |
        # Your build commands here
        echo "Building application..."
    # Add more steps as needed
